engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
   paths:
   - "src/**/*"
   - "**.php"
   - "**.module"
   - "**.inc"
   - "sugared-rim-cs"
exclude_paths:
- "tests/**/*"
